### ISSUE TITLE
Bitcoin Core 0.12.0

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#2074]
This issue is for tracking the PRs from upstream that would result in feature-parity with Bitcoin Core 0.12.0. We may not merge all of these, but we should track those we have decided not to merge alongside those we already have, so we can spot anything we might have missed.

e9d0d252fc57119766f5d7b58715451dd42b1ce6 appears to be the most common ancestor between our branch (off 0.11.2) and Bitcoin master, so all PRs listed below are based off there.

### Up to 0.11.2

- #6219 == #6218
- #6238 - same on master
- #6369 - same on master
- #6383 - 0.11-only
- #6397 - 0.11-only
- #6703 - bugfix backports
- #6750 == #6498
- #6785 == #6588
- #6707 - CLTV backport (#6351?)
- #6945 == #6917
- #6884 == #6566
- #6825 - more bugfix backports
- #6968 - 0.11.2 release notes
- #6975 - 0.11.2 7e278929df53e1fb4191bc5ba3176a177ce718bf

### Before 0.12 branch made after 3cd836c1d855b92e7c73ab31979f471c4f8dad68

In reverse order (latest merged first)

- [ ] #7158 GUI
- [ ] #7157 Cleanup
- [ ] #7128 Moving
- [ ] #6216 Wallet
- [ ] #7147 Update UniValue
- [ ] #7146 Build
- [ ] #7118 RPC docs
- [ ] #7155 Tests cleanup
- [ ] #7144 Tests
- [ ] #6872 Block & txn
- [ ] #7040 Docs
- [ ] #6898 Block & txn
- [ ] #7137 Tests
- [ ] #7141 RPC
- [ ] #7143 GUI
- [ ] #6915 Block & txn
- [ ] #7022 RPC
- [ ] #7063 Tests
- [ ] #7136 Docs cleanups
- [ ] #6914 Validation
- [ ] #7096 Wallet
- [ ] #7135 Test cleanup
- [ ] #7105 Wallet
- [ ] #7079 P2P & Net
- [ ] #7072 RPC
- [ ] #7044 RPC
- [ ] #7094 Misc
- [ ] #7008 Block & txn
- [ ] #7035 Config
- [ ] #7112 Moving, GUI
- [ ] #7103 Wallet
- [ ] #7027 GUI
- [ ] #7126 Moving
- [ ] #7116 Bugfix for #7053
- [ ] #7127 Bugfix
- [ ] #7025 GUI
- [ ] #7129 P2P & Net
- [ ] #7106 P2P & Net
- [ ] #6508 Validation
- [ ] #6961 Cleanups and bugfixes
- [ ] #6942 Docs bugfix
- [ ] #7003 Docs
- [ ] #7117 Bugfix
- [ ] #7078 Misc
- [ ] #7114 Misc
- [ ] #7090 P2P & Net
- [ ] #7095 Tests
- [ ] #7083 Bugfix - OpenSSL 1.1.0
- [ ] #6780 GUI
- [ ] #7053 Globals
- [ ] #6871 Block & txn
- [ ] #6134 Wallet
- [ ] #5967 Block & txn
- [ ] #7058 ZMQ
- [ ] #7069 Bugfix
- [ ] #7087 RPC
- [ ] #7088 Update libsecp256k1
- [ ] #7092 Build system
- [ ] #7006 GUI
- [ ] #7075 Logging
- [ ] #7066 Docs
- [ ] #7045 Tests
- [ ] #7042 Docs
- [ ] #7052 QA cleanup/build(?)
- [ ] #7065 RPC
- [ ] #7028 QA docs
- [ ] #7029 Cleanup
- [ ] #7046 P2P & Net
- [ ] #7011 RPC
- [ ] #6851 Wallet
- [ ] #6979 GUI
- [ ] #7019 CI
- [ ] #7059 Build
- [ ] #6900 Gitian determinism
- [ ] #7051 GUI
- [ ] #7048 Docs
- [ ] #7041 Docs
- [ ] #6932 Block & txn
- [ ] #6951 GUI
- [ ] #7030 Contrib cleanup
- [ ] #7050 Bugfix
- [ ] #7020 Cleanup
- [ ] #7026 Cleanup
- [ ] #6986 Correctness
- [ ] #6999 RPC
- [ ] #7023 Bugfix
- [ ] #6954 Validation
- [ ] #7016 Build
- [ ] #6991 Docs
- [ ] #7000 GUI
- [ ] #6993 Config
- [ ] #6984 P2P & Net
- ~~~#7004 Gitian~~~
- [ ] #7013 RPC
- [ ] #7010 Wallet
- [ ] #6990 RPC
- [ ] #7007 Test bugfix
- [ ] #6983 Update libsecp256k1
- [ ] #6958 Cleanup & docs
- [ ] #6998 Docs
- [ ] #6771 Policy
- [ ] #6639 P2P & Net
- [ ] #6918 Block & txn
- [ ] #6931 Validation
- [ ] #6804 Tests
- [ ] #6969 Docs
- [ ] #6974 P2P & Net
- [ ] #6987 Docs
- [ ] #6988 Docs
- [ ] #6978 Build
- [ ] #6982 Globals correctness
- [ ] #6985 Gitian
- [ ] #6965 Block & txn
- [ ] #6940 GUI labels?
- [ ] #6822 Tests
- [ ] #5574 RPC
- [ ] #6163 Globals
- ~~~#6967 Gitian?~~~
- [ ] #6908 GUI cleanup - BIP70
- [ ] #6962 Translations
- [ ] #6970 RPC
- [ ] #6955 Cleanup & docs
- [ ] #6948 Chainstate
- [ ] #6934 Block & txn
- [ ] #6887 GUI
- [ ] #6944 Update LevelDB
- [ ] #6938 Build system
- [ ] #6864 GUI
- [ ] #6669 Wallet & docs
- [ ] #6927 ZMQ
- [ ] #6933 Build docs
- [ ] #6905 Bugfix
- [ ] #6930 Build
- [ ] #6928 Revert #6566
- [ ] #6926 Tests
- ~~~#6883~~~
- [ ] #6906 Wallet
- [ ] #6896 Config
- [ ] #6863 Tests
- [ ] #6899 Correctness
- [ ] #6870 Cleanup & docs
- [ ] #6894 Tests
- [ ] #6891 Correctness
- [ ] #6892 Cleanup
- [ ] #6776 Config
- ~~~#6895 Gitian?~~~
- [ ] #6875 CI or Gitian
- [ ] #6865 Block & txn
- [ ] #6464 Block & txn
- [ ] #6889 Block & txn
- [ ] #6881 Config
- [ ] #6622 Config
- [ ] #6621 OSX
- [ ] #6888 Tests
- [x] #6566 Block & txn -> 0.11.X
- [ ] #6877 RPC
- [ ] #6813 Tests
- [ ] #6878 Docs
- [ ] #6879 Docs - BIP65
- [ ] #6873 Cleanup
- [ ] #6856 Bugfix
- [ ] #6351 Soft-fork - BIP65
- [ ] #5936 RPC
- [ ] #6818 Script
- [ ] #6790 Misc
- [ ] #6867 P2P
- [ ] #6848 Tests
- [x] #6846 Config -> #6825
- [ ] #6854 Misc
- [ ] #6859 RPC
- [ ] #6722 Block & txn
- [x] #6796 Cleanup -> #6825
- [ ] #6235 Cleanup
- [ ] #6841 Tests
- [ ] #6801 Build system
- [ ] #6827 Tests
- [ ] #6853 Tests
- [ ] #6829 Docs
- [ ] #6852 Correctness - OpenSSL
- [ ] #6837 Temp comment out rpcbind.py
- [x] #6843 Typo -> #6825
- [ ] #6849 Docs
- [ ] #6820 UniValue subdir fixes
- [ ] #6817 Docs cleanup
- [ ] #6823 Cleanup
- ~~~#6830~~~
- [ ] #6810 ZMQ
- [ ] #6777 Block & txn
- [ ] #6791 Cleanup
- [x] #6798 Test docs -> #6825
- [x] #6812 Gitian? -> #6825
- [ ] #6788 UniValue upgrade
- ~~~#6807 Gitian?~~~
- ~~~#6805 Gitian?~~~
- [ ] #6793 Dust threshold
- [ ] #6795 Disable UPnP by default
- [ ] #6789 Deps
- [ ] #6779 ZMQ
- [x] #6783 Typo -> #6825
- [ ] #6770 Cleanup
- [ ] #6720 Tests
- [ ] #6769 Bugfix cleanup
- [ ] #6650 Block & txn
- [ ] #6733 Misc
- [ ] #6762 Tests cleanup
- [ ] #6743 ZMQ
- [ ] #6760 Cleanup
- ~~~#6763 Docs~~~
- ~~~#6751 Docs~~~
- [ ] #6768 ZMQ
- [ ] #6742 Config
- [x] #6744 Build -> #6825
- [ ] #6748 Config docs
- [ ] #6759 Cleanup
- [ ] #6616 Tests
- [ ] #6739 ZMQ
- [ ] #6424 Script
- [ ] #6732 revert LibreSSL
- [ ] #6637 UniValue upgrade
- [ ] #6686 ZMQ
- [x] #5987 Misc -> #6825
- [ ] #6731 Build docs
- [x] #6588 P2P & Net -> 0.11.X
- [ ] #5924 Wallet
- [ ] #6741 Docs (maybe we want?)
- [ ] #6680 Block & txn -> ZMQ
- [ ] #6740 Docs or CI?
- [ ] #6736 ZMQ
- [ ] #6713 Misc
- [ ] #6661 Gitian docs
- [x] #6730 Tests -> #6825
- [ ] #6728 Misc
- [ ] #6719 RPC
- [ ] #6724 Bugfix - Debian
- [ ] #6718 CONTRIBUTING.md
- [ ] #5264 RPC
- [ ] #6619 Build system
- [ ] #6721 Docs
- [ ] #6664 Cleanup & bugfix -> #6825 (partial)
- [x] #6600 Build system -> #6825
- [ ] #6715 Block & txn
- [ ] #6550 Wallet
- [ ] #6653 GUI -> #6825 (partial)
- [ ] #6645 Wallet
- [x] #6688 Wallet -> #6825
- [ ] #6148 P2P & Net
- [ ] #6646 Cleanup
- [ ] #6315 GUI
- [ ] #6652 Docs
- [ ] #6647 Config
- [ ] #6694 GUI
- [x] #6709 Typo -> #6825
- [ ] #6667 Docs
- [ ] #6668 Cleanup (GUI?)
- [ ] #6671 Gitian?
- [ ] #6695 RPC
- [ ] #6654 Block & txn
- [ ] #6692 Misc
- [ ] #6422 Docs
- [ ] #6685 Tests bugfix
- [ ] #6684 ZMQ
- [ ] #6317 GUI
- [ ] #6103 Misc -> ZMQ
- [ ] #6663 Docs typo
- [ ] #5665 GUI
- [ ] #6635 Docs
- [ ] #6579 P2P & Net
- [ ] #6594 GUI
- [ ] #6640 Docs typo
- [ ] #6644 Config docs
- [ ] #6643 Docs
- [ ] #6648 RPC
- [ ] #6636 P2P & Net
- [ ] #6626 Gitian
- [ ] #6633 RPC
- [ ] #5677 RPC
- [ ] #6631 RPC docs
- [x] #6630 Misc -> #6703
- [ ] #6374 P2P & Net
- [ ] #6611 Docs
- [ ] #6627 Docs
- [ ] #6620 CI
- [x] #6617 CI -> #6703
- [ ] #6548 Tests - Windows
- [x] #6583 P2P & Net -> #6703
- [ ] #6599 Misc
- [ ] #6530 P2P & Net
- [x] #6590 Tests -> #6703
- [ ] #6576 RPC
- [ ] #6523 Tests
- [ ] #6541 Docs
- [ ] #6242 Cleanup
- [ ] #6545 Misc
- [x] #6556 P2P & Net -> #6703
- [ ] #6571 Consensus - OpenSSL
- [ ] #6544 Bugfix
- [ ] #6539 Bugfix -> #6703 (partial)
- [x] #6565 Misc -> #6703
- [ ] #6561 Misc
- [ ] #6567 Wallet
- [x] #6553 Cleanup -> #6703
- [x] #6551 Block & txn -> #6703
- [x] #6509 Tests -> #6703
- [ ] #6013 RPC
- [ ] #6415 Wallet
- [ ] #6519 Validation
- [ ] #6532 Docs
- [ ] #6346 RPC
- [ ] #6512 Docs
- [ ] #6534 Tests
- [ ] #6538 Correctness
- [ ] #6529 GUI
- [ ] #4587 GUI
- [ ] #6505 GUI
- [x] #6377 Block & txn -> #6703
- [x] #6527 Misc -> #6703
- [ ] #6177 Block & txn
- ~~~#6521~~~
- [ ] #5913 Block & txn
- [ ] #6462 Config
- [ ] #6489 Config
- [ ] #6507 Misc
- [ ] #6503 Cleanup - net
- [ ] #6504 Misc
- [x] #6498 P2P & Net -> 0.11.X
- [ ] #6284 Config
- [x] #6356 Wallet -> #6703
- [x] #6497 Misc -> #6703
- [ ] #6501 Build system -> #6703 (partial)
- [ ] #6473 Cleanup
- [ ] #6487 GUI
- [ ] #6224 Net, cleanup?
- [x] #6488 Misc -> #6703
- [ ] #6484 GUI
- [ ] #6077 Tests
- [ ] #5697 Cleanup
- [ ] #6380 RPC
- [ ] #6468 Bugfix
- [ ] #6471 GUI - Qt
- [ ] #6456 RPC
- [ ] #6465 Tests
- [ ] #6287 Tests -> #6703 (partial)
- [ ] #5515 Tests
- [ ] #6149 Misc
- [ ] #6381 Cleanup
- [ ] #6400 Docs
- [ ] #6444 Block & txn
- [ ] #6408 GUI
- [ ] #6453 Misc
- [ ] #6412 P2P & Net
- [ ] #6447 Cleanup
- [ ] #6457 RPC
- [ ] #6372 Misc
- [ ] #6439 Docs cleanup
- ~~~#6442~~~
- [ ] #6434 Build system
- [ ] #6430 Misc
- [ ] #6438 Bugfix - OpenSSL
- [x] #6440 Cleanup -> #6703
- [ ] #6373 Build system
- ~~~#6413 Docs - bdb4.8~~~
- [ ] #6433 GUI
- [ ] #6388 RPC
- [x] #6428 Tests -> #6703
- [x] #6418 Build system -> #6703
- [ ] #6398 Tests
- [ ] #6417 Tests
- [ ] #6410 Block & txn
- [ ] #6414 Tests
- ~~~#6370 Cleanup - remove DefaultMinerThreads~~~
- [ ] #6379 RPC
- [ ] #5486 RPC
- [ ] #5288 Config
- [ ] #6384 GUI - TLS
- [ ] #6401 Misc
- [ ] #6368 Tests
- [ ] #6378 GUI
- [ ] #6387 Misc
- [ ] #6390 Tests
- [ ] #6365 Moving
- [ ] #6335 Moving
- [ ] #6329 Block & txn
- [x] #6369 -> 0.11.X
- [ ] #6310 P2P & Net
- [ ] #6362 RPC
- [ ] #6361 Validation
- [ ] #5881 Tests
- [ ] #6133 Bugfix - warnings
- [ ] #6247 RPC
- [ ] #6350 Tests
- [ ] #6353 RPC
- [ ] #5994 Misc
- [ ] #6354 Gitian
- [ ] #6337 Tests
- [ ] #6299 Validation
- [ ] #6124 Block & txn
- [ ] #6333 Seeds
- [ ] #6233 Block & txn?
- [ ] #6339 RPC
- [ ] #6088 Wallet
- [ ] #6303 Gitian
- ~~~#6319 Docs - ML addr~~~
- [ ] #6318 Tests
- [ ] #6316 Cleanup - Boost
- [ ] #6262 RPC
- [ ] #6290 RPC
- [ ] #6307 RPC
- ~~~#6301 Gitian~~~
- [ ] #6305 Tests
- [ ] #6272 P2P & Net
- [ ] #6158 RPC
- [ ] #6282 Bugfix
- [ ] #6280 Bugfix - Boost 1.55
- [ ] #6286 Cleanup - bdb4
- [ ] #6271 RPC
- [ ] #6283 P2P & Net
- [ ] #6285 Bugfix - Boost
- [ ] #6274 Config - opt out of alerts
- [ ] #6269 Build system
- [ ] #6257 RPC
- [ ] #6276 RPC
- [ ] #6209 GUI
- [ ] #6256 P2P & Net
- [ ] #6266 RPC
- [ ] #6221 Block & txn
- [ ] #6264 Docs - remove translation from -help-debug
- [ ] #6061 Misc
- [ ] #5975 Misc
- [ ] #6057 Wallet
- [ ] #5985 Block & txn
- [ ] #6213 Misc
- [ ] #5927 Validation
- [ ] #6222 Block & txn
- [ ] #6244 LibreSSL
- [ ] #6239 RPC
- [ ] #6246 Cleanup - endian.h header
- [ ] #6217 GUI
- ~~~#6249 Gitian~~~
- ~~~#6250 Gitian~~~
- [ ] #6241 Bugfix - clang warnings
- ~~~#6232 Gitian~~~
- [ ] #6152 Cleanup - remove unused wallet & validation interface code
- [x] #6238 Bugfix -> 0.11.X
- [ ] #6206 Correctness - const references
- [ ] #6234 RPC
- [ ] #6121 RPC - UniValue
- ~~~#6220~~~
- [ ] #5875 P2P & Net
- [x] #6218 Build system -> 0.11.X
- ~~~#6226~~~
- [ ] #6214 Build system
- [ ] #6203 Block & txn - Remove P2SH coinbase flag
- [ ] #6210 Build system - gmp in libsecp
- [ ] #6172 P2P & Net - Ignore getheaders reqs when not synced
- [ ] #6183 Wallet - nLockTime off-by-one
- [ ] #6164 Config - -debug=1, Docs, cli help
- [ ] #6198 Docs - MAX_MONEY

## After 0.12 branch

Taken from the 0.12.0 release notes; these should be replaced with a list of PRs from the 0.12.X branch.

RPC
#7469
#7472
#7222
#7312

Config
#7440
#7290
#7386
#7323

Block & txn
#7387
#7217
#7276
#7062

P2P & Net
#7482
#7439
#7438
#7415
#7125
#7181
#7179
#7174
#7133
#7166

Validation
#7500
#6351?

Build system
#7424
#6980

Wallet
#7502
#7491
#7381
#7306
#7293
#7296
#7200
#4906

GUI
#7384
#7364
#7327
#7318
#7319
#7282
#7206
#7112

Tests
#7468
#7308
#7229
#7170
#7153
#7226
#7209
#7216

**Comment by bitcartel** [comment]
How was this list (auto)-generated?

**Comment by str4d** [comment]
`git log --merges e9d0d252..` on both Zcash and Bitcoin codebases, and then using grep / awk to extract `#XXXX` from `Merge pull request #XXXX`.

**Comment by nathan-at-least** [comment]
I just filed #2357 which is probably covered by this umbrella ticket. However, I want to pull out #2357 explicitly in order to prioritize separately from this general umbrella ticket work.
