### ISSUE TITLE
Look for TODOs and FIXME in code.

### ISSUE THREAD

**Issue by Eirik0** [zcash/zcash#3546]
From master on 10/5/18 @ 11:00AM MT:

- [ ] **wallet_nullifiers.py:162** `# TODO: Fix this during the Sapling upgrade (via #2277)` 
- [ ] **coins_tests.cpp:600** `// TODO update this or add a similar test when the SaplingNote class exist`
- [x] rpc_wallet_tests.cpp:1356 `/* TODO: Uncomment during PR for #3388` #3517
- [x] asyncoperation_shieldcoinbase:78 `// TODO: Add Sapling support. For now, ensure we can freely convert.` #3518 
- [x] test_wallet_zkeys.cpp:291 `/* TODO: Uncomment during PR for #3388` #3517
- [x] rpcwallet.cpp:2537 `// TODO: Add Sapling support. For now, ensure we can freely convert.` #3510
- [x] rpcwallet.cpp:2556 `// TODO: Add Sapling support` #3510
- [x] rpcwallet.cpp:2586 `// TODO: Sapling` #3510
- [x] rpcwallet.cpp:3310 `// TODO: Add Sapling support. For now, ensure we can freely convert.` #3499
- [x] rpcwallet.cpp:3338 `// TODO: Sapling` #3499
- [x] rpcwallet.cpp:3789 `// TODO Check whether the recipient is a Sprout or Sapling address` #3567
- [x] wallet.cpp:88 `// TODO: Add Sapling support` (Handled by GenerateNewSaplingZKey) #3579
- [x] wallet.cpp:169 `// TODO: Persist to disk` #3517
- [x] wallet.cpp:305 `// TODO: Sapling - Write to disk` #3517
- [x] wallet.cpp:1932 `/* TODO: Uncomment during PR for #3388` #3517
- [x] wallet.cpp:1953 `/* TODO: Uncomment during PR for #3388` #3517
- [x] wallet.cpp:1968 `/* TODO: Uncomment during PR for #3388` #3517
- [x] main.cpp:5486 // TODO: currently, prohibit joinsplits from entering mapOrphans #3567

N/A for 2.0.1:
- [x] **asyncoperation_mergetoaddress.cpp:85** `// TODO: Add Sapling support. For now, return an error to the user.` (N/A for 2.0.1) #3619 
- [x] **asyncoperation_mergetoaddress.cpp:333** `// TODO: Add Sapling support. For now, return an error to the user.` (N/A for 2.0.1) #3619 
- [ ] **rpcdump.cpp:727** `// TODO: Add Sapling support. For now, return an error to the user.` (N/A for 2.0.1)
- [ ] **rpcdump.cpp:829** `// TODO: Add Sapling support. For now, return an error to the user.` (N/A for 2.0.1)
- [x] **rpcwallet.cpp:4362** `// TODO: Add Sapling support` (N/A for 2.0.1 not supported for Sapling)  #3619 
- [ ] **wallet.cpp:1226** `// TODO: Sapling.  This method is only called from RPC walletpassphrase, which is currently unsupported`  (N/A for 2.0.1)
- [x] **wallet.cpp:4437** `// TODO: Add locking for Sapling notes`  (N/A for 2.0.1) #3619

**Comment by bitcartel** [comment]
From rocketchat:
```
if (tx.vjoinsplit.size() > 0) {
        return MAX_PRIORITY;
    }
```
in coins.cpp:625.

Update for Sapling with:
```
if (!tx.vjoinsplit.empty() || !tx.vShieldedSpend.empty() || tx.vShieldedOutput.empty()) {
 return MAX_PRIORITY;
}
```

**Comment by Eirik0** [comment]
Many of these items currently have PRs in review (which is noted above). The items marked in bold are ones which I couldn't immediately find a PR for. #3216 is an issue for updating asyncoperation_mergetoaddress, but I am not sure about the other items.

**Comment by daira** [comment]
Thanks for doing this @Eirik0.

**Comment by mdr0id** [comment]
TY @Eirik0 !

FWIW, the persist / Sapling - write to disk TODOs are actively being implemented, so I have marked these accordingly in the original comment.

**Comment by bitcartel** [comment]
main.cpp:5486:        // TODO: currently, prohibit joinsplits from entering mapOrphans

        // TODO: currently, prohibit joinsplits from entering mapOrphans
        else if (fMissingInputs && tx.vjoinsplit.size() == 0)
        {
            AddOrphanTx(tx, pfrom->GetId());

            // DoS prevention: do not allow mapOrphanTransactions to grow unbounded
            unsigned int nMaxOrphanTx = (unsigned int)std::max((int64_t)0, GetArg("-maxorphantx", DEFAULT_MAX_ORPHAN_TRANSACTIONS));
            unsigned int nEvicted = LimitOrphanTxSize(nMaxOrphanTx);
            if (nEvicted > 0)
                LogPrint("mempool", "mapOrphan overflow, removed %u tx\n", nEvicted);
        } else {

**Comment by bitcartel** [comment]
@str4d Do we still need to do this check?
wallet/rpcwallet.cpp:3789:        // TODO Check whether the recipient is a Sprout or Sapling address

    // As a sanity check, estimate and verify that the size of the transaction will be valid.
    // Depending on the input notes, the actual tx size may turn out to be larger and perhaps invalid.
    size_t txsize = 0;
    for (int i = 0; i < zaddrRecipients.size(); i++) {
        // TODO Check whether the recipient is a Sprout or Sapling address
        JSDescription jsdesc;

        if (mtx.fOverwintered && (mtx.nVersion >= SAPLING_TX_VERSION)) {
            jsdesc.proof = GrothProof();
        }

        mtx.vjoinsplit.push_back(jsdesc);
    }

**Comment by bitcartel** [comment]
wallet/wallet.cpp:88:    // TODO: Add Sapling support

This comment looks redundant:

libzcash::PaymentAddress CWallet::GenerateNewZKey()
{
    AssertLockHeld(cs_wallet); // mapSproutZKeyMetadata
    // TODO: Add Sapling support
    auto k = SproutSpendingKey::random();
    auto addr = k.address();

as new function below adds Sapling support:

// Generate a new Sapling spending key and return its public payment address
SaplingPaymentAddress CWallet::GenerateNewSaplingZKey()
{

**Comment by str4d** [comment]
@bitcartel yep, that's an outdated comment. Note that `libzcash::PaymentAddress CWallet::GenerateNewZKey()` returns the generic type, not a direct Sprout address. Originally I thought we might use that function for both Sprout and Sapling, but now we have separate functions.

**Comment by Eirik0** [comment]
I was a little bit confused by the `GenerateNewZKey` method too, so I created https://github.com/zcash/zcash/issues/3577 to make it more clear what is going on. I will submit a PR for this shortly after the sapling persistence PR has been merged.

**Comment by Eirik0** [comment]
Edited the description: Things marked N/A for 2.0.1 have their own section.

**Comment by Eirik0** [comment]
It is no longer necessary to keep this ticket open. The remaining TODOs will be dealt with individually.
