### ISSUE TITLE
Sprout Deprecation roadmap

### ISSUE THREAD

**Issue by jackgavigan** [zcash/zcash#3788]
The purpose of this ticket is to define a roadmap towards the ultimate goal of deprecating the Sprout value pool. This comment will be edited so that the steps listed below represent the current plan for achieving this goal. 

- [x] #3671 - Make “sapling” the default for RPC “z_getnewaddress”
- [ ] #3752 - Remove ability to create new Sprout addresses
- [ ] #3773 - Remove the ability to send to Sprout addresses
- [ ] _Change getblocktemplate to ignore transactions that send to Sprout addresses?_
- [ ] _Consensus change to prohibit sending to Sprout addresses? (c.f. #3677 - Sprout Address Retirement feature requirements)_
- [ ] _Deprecate the Sprout value pool entirely? (c.f. #3787)_

Steps in _italic_ are not yet well-defined and require further discussion. 

Each step will involve communicating with the Zcash eco-system to assess the user impact and telegraph the planned changes to give any affected users time to prepare.

**Comment by nathan-at-least** [comment]
https://github.com/zcash/zips/pull/214 is a ZIP which implements (a variant of) `#3677 - Consensus change to prohibit sending to Sprout addresses`. However, that ticket number isn't a live link for me, not sure why. Is that the right issue number, @daira ?
