### ISSUE TITLE
zcashd 2.1.0 release

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#4191]
- [x] Set Blossom activation height
- [x] Run the release script release
- [x] Merge
- [x] Tag
- [x] Notify ECC dev inf team for packaging
- [x] Notify ECC comms team for annoucements
