### ISSUE TITLE
Deploy NU3

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#4205]
Tasks:
- [ ] Define a schedule.
- [x] Pick an awesome codename for NU3 that everyone loves.
- [x] Change zcashd for the concept of NU3.
- [x] Review / merge MMR stuff in librustzcash.
- [ ] Implement zcashd changes for MMR if that's an ECC responsibility.
- [ ] Review / merge MMR stuff in zcashd.
- [x] Add tests to shielded coinbase PR.
- [ ] Review/Merge shielded coinbase PR.
- [ ] Set testnet activation height.
- [ ] testnet deployment and testing.
- [ ] Coordinate with known third parties that are integration risks (mining pools, especially anyone generating block templates not going through zcashd).
- [ ] Set mainnet activation height.
