### ISSUE TITLE
[Orchard] Consensus specification

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4707]
This is a tracking ticket for all specification issues related to the Halo-2-based Sapling variant codenamed Orchard. For instance:

* [x] #4708: Poseidon (core permutation and modes)
* [x] #4709: RedPallas
* [x] #4710: GroupHash into Pallas
* [x] #4711: Shielded protocol changes relative to Sapling. For example,
  * we probably no longer want to use MixingPedersenHash
  * cofactor multiplication is not necessary for Tweedledee
* [x] #4712: Note encryption
* [x] #4713: Commitment Merkle tree design
* [x] #4714: Encoding of Halo 2 proofs
* [x] #4715: Encoding of keys and addresses
* [x] #4716: Transaction format and hashing changes
* [x] #4727: Hash extractor for Tweedle curves
* [x] zcash/zips#396: Refactoring the protocol specification
* [x] [zcash/orchard#54](https://app.zenhub.com/workspace/o/zcash/orchard/issues/54) Document ECC gadget in circuit

**Comment by daira** [comment]
See also #4718 (Choose a name for Sapling-on-Halo-2).
