### ISSUE TITLE
Review rpcwallet.cpp and rpcdump.cpp for updates needed for Orchard

### ISSUE THREAD

**Issue by daira** [zcash/zcash#5605]
Check each item if it is covered by an existing issue, and link the issue number.

`rpcwallet.cpp`:
* [x] `listaddresses` (#5515)
* [x] `gettransaction` (#5682)
* [x] `z_listunspent` (#5683)
* [x] `z_getnewaddress` (document to use `z_getnewaccount` & `z_getaddressforaccount` instead) (#5684)
* [x] `z_getbalance` (#5666)
* [x] `z_getbalanceforviewingkey`
* [x] `z_getbalanceforaccount`
* [x] `z_gettotalbalance`
* [x] `z_viewtransaction` (#5186)
* [x] `z_shieldcoinbase` (#5511)
* [x] `z_mergetoaddress` (#5685)
* [x] `z_getnotescount` (add count of Orchard notes) (#5684)

`rpcdump.cpp`:
* [x] `z_importkey` (make clear in help that Orchard keys can't be individually imported) (#5686)
* [x] `z_exportkey` (#5686)
* [x] `z_importviewingkey` (#5687)
* [x] `z_exportviewingkey` (#5687)

**Comment by steven-ecc** [comment]
`z_getaddressforaccount` needs to be updated to return an Orchard receiver. Currently sapling and transparent, but I believe that support is in a branch already.

**Comment by nuttycom** [comment]
Completed in pairing with @daira. See #5684
