### ISSUE TITLE
Add tests that depend upon completed Orchard wallet functionality.

### ISSUE THREAD

**Issue by nuttycom** [zcash/zcash#5648]
Review existing wallet test cases and add a checklist to this issue to ensure that wallet behavior is fully tested for transactions involving Orchard.
- [x] Orchard spends that roll back across the activation boundary; ensure that the mempool ends up in the correct state. Fixed by #5752 
- [x] Add a unit test that ensures that the same nullifier can't be spent twice in a single transaction. Fixed by #5761
- [x] Add an RPC test that checks attempted double-spends across a network partition. Fixed by #5764

**Comment by nuttycom** [comment]
#5761 and #5764 resolved the remaining open questions.
