### ISSUE TITLE
Zcashd consensus implementation for NU6

### ISSUE THREAD

**Issue by daira** [zcash/zcash#6870]
* [x] ZIP 236 was implemented in #6933
* ZIP 1015 / ZIP 214
  * [x] Lockbox funding streams in #6912 and #6940
  * [x] Testnet addresses #6941
  * [x] Mainnet addresses
* [x] Testnet activation height in #6941, released in zcashd 5.10.0, activated on 2024-08-28 17:37:30Z
* [x] Mainnet activation height will be set in zcashd 6.0.0

**Comment by zancas** [comment]
Is it our intention to deprecate zcashd before NU6 activation?

**Comment by daira** [comment]
> Is it our intention to deprecate zcashd before NU6 activation?

No. The current plan is to deprecate it before NU7 activation.

**Comment by nuttycom** [comment]
Completed in #6958
