### ISSUE TITLE
study feasibility of reducing libsnark memory usage for proving

### ISSUE THREAD

**Issue by daira** [zcash/zcash#750]
This ticket covers ways of reducing memory usage of proving by implementation changes to libsnark, other than changing the circuit.

See also:
- [ ] #561 investigate whether the zkSNARK can use only x coordinates (or only y coordinates)
- [x] #748 Buildbot Performance Measurement
- [ ] #605 Add `--debug=libsnark-profiling` option.
- [ ] #251 Benchmark and document the time/memory tradeoff of LOWMEM=1
- [x] #2235 Stream the proving key to reduce memory usage

It does not cover computing the witness which was #20 and #473 (done).

**Comment by ebfull** [comment]
Couple things:

We copy `vector<FieldT>`'s around several times both outside and inside of libsnark's API. I'm unsure of how bulky this is (will check it out with massif) but this is definitely low hanging fruit for us. (In addition, we should use the libsnark API to reduce memory usage by throwing away objects we're no longer using like gadgets or the protoboard.)

**Comment by daira** [comment]
I'm very concerned that mitigating the attacks mentioned on #714 will increase the cost of proving to the point that we *have* to do some of the performance enhancements we've talked about (#896, this ticket, #647) before launch.

**Comment by zookozcash** [comment]
@daira: What does it take to close this ticket? Do we need to close the 4 sub-tickets?

**Comment by daira** [comment]
This is an umbrella ticket, it's for keeping track of the subtickets that affect memory usage of proving and discussing how they interact, or brainstorming new ideas (like @ebfull's comment about ``vector<FieldT>``s for example). It can be closed when we decide that's no longer useful.
